# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_delete_receipts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartitems', models.IntegerField()),
                ('date', models.DateField()),
                ('loyalty_id', models.IntegerField()),
                ('receipt_id', models.IntegerField()),
            ],
        ),
    ]
