# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='turnover',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='cartitems',
            field=models.TextField(),
        ),
    ]
